/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAlmoxarifadoRouteImport } from './routes/_authenticated/almoxarifado'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedSuporteRouteImport } from './routes/_authenticated/suporte'
import { Route as AuthenticatedAtualizacoesIdRouteImport } from './routes/_authenticated/atualizacoes.$id'
import { Route as AuthenticatedObrasIdRouteImport } from './routes/_authenticated/obras.$id'
import { Route as AuthenticatedObrasIdNovaAtualizacaoRouteImport } from './routes/_authenticated/obras_.$id.nova-atualizacao'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlmoxarifadoRoute =
  AuthenticatedAlmoxarifadoRouteImport.update({
    id: '/almoxarifado',
    path: '/almoxarifado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuporteRoute = AuthenticatedSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtualizacoesIdRoute =
  AuthenticatedAtualizacoesIdRouteImport.update({
    id: '/atualizacoes/$id',
    path: '/atualizacoes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedObrasIdRoute = AuthenticatedObrasIdRouteImport.update({
  id: '/obras/$id',
  path: '/obras/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasIdNovaAtualizacaoRoute =
  AuthenticatedObrasIdNovaAtualizacaoRouteImport.update({
    id: '/obras_/$id/nova-atualizacao',
    path: '/obras/$id/nova-atualizacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/almoxarifado': typeof AuthenticatedAlmoxarifadoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/atualizacoes/$id': typeof AuthenticatedAtualizacoesIdRoute
  '/obras/$id': typeof AuthenticatedObrasIdRoute
  '/obras/$id/nova-atualizacao': typeof AuthenticatedObrasIdNovaAtualizacaoRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/almoxarifado': typeof AuthenticatedAlmoxarifadoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/atualizacoes/$id': typeof AuthenticatedAtualizacoesIdRoute
  '/obras/$id': typeof AuthenticatedObrasIdRoute
  '/obras/$id/nova-atualizacao': typeof AuthenticatedObrasIdNovaAtualizacaoRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/almoxarifado': typeof AuthenticatedAlmoxarifadoRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/suporte': typeof AuthenticatedSuporteRoute
  '/_authenticated/atualizacoes/$id': typeof AuthenticatedAtualizacoesIdRoute
  '/_authenticated/obras/$id': typeof AuthenticatedObrasIdRoute
  '/_authenticated/obras_/$id/nova-atualizacao': typeof AuthenticatedObrasIdNovaAtualizacaoRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/redefinir-senha'
    | '/admin'
    | '/almoxarifado'
    | '/painel'
    | '/suporte'
    | '/atualizacoes/$id'
    | '/obras/$id'
    | '/obras/$id/nova-atualizacao'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/redefinir-senha'
    | '/admin'
    | '/almoxarifado'
    | '/painel'
    | '/suporte'
    | '/atualizacoes/$id'
    | '/obras/$id'
    | '/obras/$id/nova-atualizacao'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/redefinir-senha'
    | '/_authenticated/admin'
    | '/_authenticated/almoxarifado'
    | '/_authenticated/painel'
    | '/_authenticated/suporte'
    | '/_authenticated/atualizacoes/$id'
    | '/_authenticated/obras/$id'
    | '/_authenticated/obras_/$id/nova-atualizacao'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/almoxarifado': {
      id: '/_authenticated/almoxarifado'
      path: '/almoxarifado'
      fullPath: '/almoxarifado'
      preLoaderRoute: typeof AuthenticatedAlmoxarifadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suporte': {
      id: '/_authenticated/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AuthenticatedSuporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atualizacoes/$id': {
      id: '/_authenticated/atualizacoes/$id'
      path: '/atualizacoes/$id'
      fullPath: '/atualizacoes/$id'
      preLoaderRoute: typeof AuthenticatedAtualizacoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras/$id': {
      id: '/_authenticated/obras/$id'
      path: '/obras/$id'
      fullPath: '/obras/$id'
      preLoaderRoute: typeof AuthenticatedObrasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras_/$id/nova-atualizacao': {
      id: '/_authenticated/obras_/$id/nova-atualizacao'
      path: '/obras/$id/nova-atualizacao'
      fullPath: '/obras/$id/nova-atualizacao'
      preLoaderRoute: typeof AuthenticatedObrasIdNovaAtualizacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlmoxarifadoRoute: typeof AuthenticatedAlmoxarifadoRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedSuporteRoute: typeof AuthenticatedSuporteRoute
  AuthenticatedAtualizacoesIdRoute: typeof AuthenticatedAtualizacoesIdRoute
  AuthenticatedObrasIdRoute: typeof AuthenticatedObrasIdRoute
  AuthenticatedObrasIdNovaAtualizacaoRoute: typeof AuthenticatedObrasIdNovaAtualizacaoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlmoxarifadoRoute: AuthenticatedAlmoxarifadoRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedSuporteRoute: AuthenticatedSuporteRoute,
  AuthenticatedAtualizacoesIdRoute: AuthenticatedAtualizacoesIdRoute,
  AuthenticatedObrasIdRoute: AuthenticatedObrasIdRoute,
  AuthenticatedObrasIdNovaAtualizacaoRoute:
    AuthenticatedObrasIdNovaAtualizacaoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
